### ISSUE TITLE
using Foundatio's latest version 10.0.1 breaks the Aix.FoundatioEx

### ISSUE THREAD

**Issue by MatheswaranSagadevan** [linzhiqiang/Aix.FoundatioEx#2]
Hi,
We are using Foundatio and Foundatio.Redis for different functionalities.
We also use Aix.FoundatioEx for kafka communications.

Now, we are trying to upgrade Foundatio to its latest version 10.0.1. when we did, our application is breaking in Aix.FoundatioEx error saying issue in MessagePack serializer couldn't load assembly. and it is right.
The latest Foundatio does not have Message pack serializer but your library internally uses Foundatio's 8.1.2058 which internally uses message serializer.

kindly help us upgrading your libraries to latest Foundatio.

**Comment by linzhiqiang** [comment]
please&nbsp;Install-Package Aix.FoundatioMessagingEx.Kafka -Version 1.0.7


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linzhiqiang/Aix.FoundatioEx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月17日(星期二) 下午4:15
收件人:&nbsp;"linzhiqiang/Aix.FoundatioEx"<Aix.FoundatioEx@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[linzhiqiang/Aix.FoundatioEx] using Foundatio's latest version 10.0.1 breaks the Aix.FoundatioEx (#2)





 
Hi,
 We are using Foundatio and Foundatio.Redis for different functionalities.
 We also use Aix.FoundatioEx for kafka communications.
 
Now, we are trying to upgrade Foundatio to its latest version 10.0.1. when we did, our application is breaking in Aix.FoundatioEx error saying issue in MessagePack serializer couldn't load assembly. and it is right.
 The latest Foundatio does not have Message pack serializer but your library internally uses Foundatio's 8.1.2058 which internally uses message serializer.
 
kindly help us upgrading your libraries to latest Foundatio.

**Comment by MatheswaranSagadevan** [comment]
Hi, Thanks for quick response. 
But I have an issue.
The Aix.FoundatioMessagingEx.Kafka v1.0.7 supports only .net standard2 dependencies. but I so far used a project with .net framework 4.7 which internally had dependent references with our legacy c++ libraries.

do you have any temporary fix to support .net frameworks projects

**Comment by linzhiqiang** [comment]
Which version do you use？
Microsoft.Extensions.Logging


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linzhiqiang/Aix.FoundatioEx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月20日(星期五) 下午4:26
收件人:&nbsp;"linzhiqiang/Aix.FoundatioEx"<Aix.FoundatioEx@noreply.github.com&gt;;
抄送:&nbsp;"林志强"<360779475@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [linzhiqiang/Aix.FoundatioEx] using Foundatio's latest version 10.0.1 breaks the Aix.FoundatioEx (#2)





 
Hi, Thanks for quick response.
 But I have an issue.
 The Aix.FoundatioMessagingEx.Kafka v1.0.7 supports only .net standard2 dependencies. but I so far used a project with .net framework 4.7 which internally had dependent references with our legacy c++ libraries.
 
do you have any temporary fix to support .net frameworks projects

**Comment by MatheswaranSagadevan** [comment]
![image](https://user-images.githubusercontent.com/54369119/99785465-09274780-2ad2-11eb-8e88-b71a0b304849.png)

**Comment by MatheswaranSagadevan** [comment]
Microsoft.Extensions.Logging --> v5

**Comment by MatheswaranSagadevan** [comment]
any updates...?
Did you make your library to work for .net framework ?

**Comment by linzhiqiang** [comment]
Please&nbsp; "Install-Package Aix.FoundatioMessagingEx.Kafka -Version 1.0.8"


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linzhiqiang/Aix.FoundatioEx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月23日(星期一) 下午3:43
收件人:&nbsp;"linzhiqiang/Aix.FoundatioEx"<Aix.FoundatioEx@noreply.github.com&gt;;
抄送:&nbsp;"林志强"<360779475@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [linzhiqiang/Aix.FoundatioEx] using Foundatio's latest version 10.0.1 breaks the Aix.FoundatioEx (#2)





 
any updates...?
 Did you make your library to work for .net framework ?

**Comment by MatheswaranSagadevan** [comment]
Hi Linzhiqiang,
I have already noticed that you published new version with .net standard 2.0 to support our requirement.
My sincere thanks to your support.

one more request from my end:
As I informed in our previous discussion, we are using Microsoft.Extensions.Logging with Version 5.0, but your library refers to version 3.1.0.

Due to this we face System.Io. exception in MessageBus class so the consume fails.
  private string GetTopic(Type type)
        {
            return **Helper.GetTopic(_kafkaOptions, type);**
        }

Once I downgrade my logging version to 3.1.0 it works. Unfortunately we have requirement to use logging with 5.0 so that our other requirements will get fulfilled.

Could you please **upgrade** your logging framework to **Microsoft.Extension.Logging to Version 5.0**..? it is kind of important to us.

**Comment by linzhiqiang** [comment]
Please&nbsp; "Install-Package Aix.FoundatioMessagingEx.Kafka -Version 1.0.10"




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linzhiqiang/Aix.FoundatioEx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月25日(星期三) 晚上10:23
收件人:&nbsp;"linzhiqiang/Aix.FoundatioEx"<Aix.FoundatioEx@noreply.github.com&gt;;
抄送:&nbsp;"林志强"<360779475@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [linzhiqiang/Aix.FoundatioEx] using Foundatio's latest version 10.0.1 breaks the Aix.FoundatioEx (#2)





 
Hi Linzhiqiang,
 I have already noticed that you published new version with .net standard 2.0 to support our requirement.
 My sincere thanks to your support.
 
one more request from my end:
 As I informed in our previous discussion, we are using Microsoft.Extensions.Logging with Version 5.0, but your library refers to version 3.1.0.
 
Due to this we face System.Io. exception in MessageBus class so the consume fails.
 private string GetTopic(Type type)
 {
 return Helper.GetTopic(_kafkaOptions, type);
 }
 
Once I downgrade my logging version to 3.1.0 it works. Unfortunately we have requirement to use logging with 5.0 so that our other requirements will get fulfilled.
 
Could you please upgrade your logging framework to Microsoft.Extension.Logging to Version 5.0..? it is kind of important to us.

**Comment by MatheswaranSagadevan** [comment]
Many many thanks. It worked 👍
